load(file = "data/Bird_Sighting_Texas_2018.rda")
#Reads data into environment
sapply(Bird_Sighting_Texas_2018, function(x) length(unique(x)))
#Counts the number of unique entries for each of the columns therefore telling us the number of species seen
Birds.sorted <- Bird_Sighting_Texas_2018[order(Bird_Sighting_Texas_2018$taxon_family_name),]
#sorts data-frame alphabetically by family names
Accipitridae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Accipitridae')
Aegithalidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Aegithalidae')
Alaudidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Alaudidae')
Alcedinidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Alcedinidae')
Anatidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Anatidae')
Anhingidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Anhingidae')
Apodidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Apodidae')
Ardeidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Ardeidae')
Bombycillidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Bombycillidae')
Cacatuidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Cacatuidae')
Calcariidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Calcariidae')
Caprimulgidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Caprimulgidae')
Cardinalidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Cardinalidae')
Cathartidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Cathartidae')
Certhiidae	<- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Certhiidae')
Charadriidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Charadriidae')
Ciconiidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Ciconiidae')
Columbidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Columbidae')
Corvidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Corvidae')
Cracidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Cracidae')
Cuculidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Cuculidae')
Estrildidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Estrildidae')
Falconidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Falconidae')
Fregatidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Fregatidae')
Fringillidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Fringillidae')
Gaviidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Gaviidae')
Gruidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Gruidae')
Haematopodidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Haematopodidae')
Hirundinidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Hirundinidae')
Hydrobatidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Hydrobatidae')
Icteridae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Icteridae')
Icteriidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Icteriidae')
Jacanidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Jacanidae')
Laniidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Laniidae')
Laridae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Laridae')
Mimidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Mimidae')
Motacillidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Motacillidae')
Numididae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Numididae')
Odontophoridae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Odontophoridae')
Pandionidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Pandionidae')
Paridae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Paridae')
Parulidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Parulidae')
Passerellidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Passerellidae')
Passeridae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Passeridae')
Pelecanidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Pelecanidae')
Phalacrocoracidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Phalacrocoracidae')
Phasianidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Phasianidae')
Picidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Picidae')
Podicipedidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Podicipedidae')
Polioptilidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Polioptilidae')
Psittacidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Psittacidae')
Psittaculidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Psittaculidae')
Ptiliogonatidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Ptiliogonatidae')
Pycnonotidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Pycnonotidae')
Rallidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Rallidae')
Recurvirostridae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Recurvirostridae')
Regulidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Regulidae')
Remizidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Remizidae')
Scolopacidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Scolopacidae')
Sittidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Sittidae')
Stercorariidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Stercorariidae')
Strigidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Strigidae')
Sturnidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Sturnidae')
Sulidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Sulidae')
Thraupidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Thraupidae')
Threskiornithidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Threskiornithidae')
Tityridae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Tityridae')
Trochilidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Trochilidae')
Troglodytidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Troglodytidae')
Trogonidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Trogonidae')
Turdidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Turdidae')
Tyrannidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Tyrannidae')
Tytonidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Tytonidae')
Vireonidae <- sum(Bird_Sighting_Texas_2018$taxon_family_name == 'Vireonidae')
#Logic tests to count each appearance of the avian families
Family <- c('Accipitridae', 'Aegithalidae', 'Alaudidae', 'Alcedinidae', 'Anatidae', 'Anhingidae', 'Apodidae', 'Ardeidae', 'Bombycillidae', 'Cacatuidae', 'Calcariidae', 'Caprimulgidae', 'Cardinalidae', 'Cathartidae', 'Certhiidae', 'Charadriidae', 'Ciconiidae', 'Columbidae', 'Corvidae', 'Cracidae', 'Cuculidae', 'Estrildidae', 'Falconidae', 'Fregatidae', 'Fringillidae', 'Gaviidae', 'Gruidae', 'Haematopodidae', 'Hirundinidae', 'Hydrobatidae', 'Icteridae', 'Icteriidae', 'Jacanidae', 'Laniidae', 'Laridae', 'Mimidae', 'Motacillidae', 'Numididae', 'Odontophoridae', 'Pandionidae', 'Paridae', 'Parulidae', 'Passerellidae', 'Passeridae', 'Pelecanidae', 'Phalacrocoracidae', 'Phasianidae', 'Picidae', 'Podicipedidae', 'Polioptilidae', 'Psittacidae', 'Psittaculidae', 'Ptiliogonatidae', 'Pycnonotidae', 'Rallidae', 'Recurvirostridae', 'Regulidae', 'Remizidae', 'Scolopacidae', 'Sittidae', 'Stercorariidae', 'Strigidae', 'Sturnidae', 'Sulidae', 'Thraupidae', 'Threskiornithidae', 'Tityridae', 'Trochilidae', 'Troglodytidae', 'Trogonidae', 'Turdidae', 'Tyrannidae', 'Tytonidae', 'Vireonidae')
#Assigns all family names as a vector
Numbers <- c(5309, 15, 38, 602, 10487, 254, 71, 9544, 696, 3, 4, 275, 5017, 2510, 58, 1445, 82, 4363, 2120, 190, 654, 77, 1521, 24, 2545, 63, 304, 143, 1080, 1, 5291, 66, 4, 458, 2788, 2854, 170, 10, 211, 600, 1650, 3668, 5639, 1132, 1346, 1294, 587, 3220, 930, 247, 245, 4, 26, 13, 1491, 616, 624, 63, 3374, 141, 1, 942, 755, 45, 16, 1103, 3, 977, 1473, 10, 2795, 4579, 50, 635)
#Assigns each of the discovered appearance numbers to its own vector
Texas.family <- data.frame(Family = Family, Number.seen = Numbers)
#Combines the two previous vectors into one data-frame and name assigned
attach(Texas.family)
#attached to R search path
par(mar = c(2,4,2,2), mfrow = c(1,1))
#adjusts plot margins (bottom, left, top, right)
barplot(Texas.family$Number.seen, names.arg = Texas.family$Family, main = 'Bird families seen in Texas 2018', horiz = TRUE, cex.names = 0.25, las = 1, cex.axis = 0.8, xlim = c(0,12000))
#plots all families against number seen, not the most readable graph
Texas.family <- Texas.family[order(-Texas.family$Number.seen),]
#resorts by descending number seen
head(Texas.family, 10)
#displays the top 10 values
Top.Ten <- subset(Texas.family, Number.seen >= 3374)
#puts the top 10 in it's own data set
par(mar = c(4,7,4,3))
#alters the margins to better suit graph
colours <- c('red','pink','orange','yellow','dark green','blue','purple','violet','light grey','black')
#Creates a rainbow vector for graph colouring
barplot(Top.Ten$Number.seen, names.arg = Top.Ten$Family, main = 'Top 10 most commonly sighted bird families, Texas 2018', horiz = TRUE, las = 1, xlim = c(0,12000), cex.main = 0.9, xlab = 'Number seen', col = colours)
#plots an easier to read graph of the most common family sightings
